[web]
web-01.ru-central1.internal
web-02.ru-central1.internal

[web:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[db_primary]
db-01.ru-central1.internal

[db_primary:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[db_standby]
db-02.ru-central1.internal

[db_standby:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[postgres:children]
db_primary
db_standby


[zabbix]
zabbix.ru-central1.internal

[zabbix:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[bastion]
bastion.ru-central1.internal

[bastion:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[elasticsearch]
elasticsearch.ru-central1.internal

[elasticsearch:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[kibana]
kibana.ru-central1.internal

[kibana:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/diploma_yc


[zabbix_agents:children]
web
bastion
zabbix
elasticsearch
kibana
postgres
